name: Check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    needs: [lint]
    strategy:
      matrix:
        versions: [22, 20, 24]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.versions }}

      - name: Install
        run: npm ci

      - name: Test
        env:
          PORT: ${{ secrets.PORT }}
        run: npm run test
